name: Get Citation Data

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate Empty Citation Data
      run: |
        mkdir -p ./google_scholar_crawler/results
        echo '{"name": "Empty Data", "citedby": 0, "publications": {}, "updated": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}' > ./google_scholar_crawler/results/gs_data.json
        echo '{"schemaVersion": 1, "label": "citations", "message": "0"}' > ./google_scholar_crawler/results/gs_data_shieldsio.json
        cd ./google_scholar_crawler/results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data - $(date)"
        git push "${remote_repo}" HEAD:google-scholar-stats --force